// Shared drivers data that can be used across components
const drivers = [
  {
    id: 0,
    name: "Cabral 422",
    city: "Negombo",
    experience: 5,
    vehicle: "Car (2 Pax)",
    contact: "+94 71 123 4567",
    image: "/images/driver1.jpg",
    rating: 5,
    reviews: 4,
    location: "Negombo",
    license: "Private Chauffeur Guide",
    verified: true,
    recommended: false,
    availability: "Available",
    email: "cabral422@email.com",
    mobile: "+94 71 123 4567",
    booked: false,
    // Array to track when driver is booked
    bookings: [],
  },
  {
    id: 1,
    name: "Silva 012",
    city: "Colombo",
    experience: 7,
    vehicle: "Car (2 Pax)",
    contact: "+94 77 222 3333",
    image: "/images/driver2.jpg",
    rating: 4,
    reviews: 8,
    location: "Colombo",
    license: "Private Chauffeur Guide",
    verified: true,
    recommended: true,
    availability: "Available",
    email: "silva012@email.com",
    mobile: "+94 77 222 3333",
    booked: false,
    bookings: [],
  },
  {
    id: 2,
    name: "Fernando 024",
    city: "Kandy",
    experience: 6,
    vehicle: "Van (8 Pax)",
    contact: "+94 76 555 7777",
    image: "/images/driver3.jpg",
    rating: 5,
    reviews: 12,
    location: "Kandy",
    license: "Private Chauffeur Guide",
    verified: true,
    recommended: true,
    availability: "Available",
    email: "fernando024@email.com",
    mobile: "+94 76 555 7777",
    booked: false,
    bookings: [],
  },
];

export default drivers;
