// Shared guides data that can be used across components
const guides = [
  {
    id: 0,
    name: "Ayesha Kumar",
    image: "/images/guide1.jpg",
    rating: 5,
    availability: "Available",
    languages: ["English", "Sinhala", "Tamil"],
    hometown: "Colombo",
    city: "Colombo",
    experience: 4,
    email: "ayesha.kumar@email.com",
    mobile: "+94 77 987 6543",
    contact: "+94 77 987 6543",
    reviews: 25,
    booked: false,
    specialization: "Cultural Tours",
    location: "Kandy",
    bookings: [],
  },
  {
    id: 1,
    name: "Rohan Perera",
    image: "/images/guide2.jpg",
    rating: 4,
    availability: "Available",
    languages: ["English", "Sinhala"],
    hometown: "Kandy",
    city: "Kandy",
    experience: 6,
    email: "rohanp@email.com",
    mobile: "+94 76 111 2233",
    contact: "+94 76 111 2233",
    reviews: 17,
    booked: false,
    specialization: "Cultural Tours",
    location: "Jaffna",
    bookings: [],
  },
  {
    id: 2,
    name: "Priya Silva",
    image: "/images/guide3.jpg",
    rating: 5,
    availability: "Available",
    languages: ["English", "Sinhala", "German"],
    hometown: "Galle",
    city: "Galle",
    experience: 5,
    email: "priya.silva@email.com",
    mobile: "+94 71 888 9999",
    contact: "+94 71 888 9999",
    reviews: 30,
    booked: false,
    specialization: "Cultural Tours",
    location: "colombo",
    bookings: [],
  },
];

export default guides;
